export const colorFamily = [
  'green-tilleul-verveine',
  'green-bourgeon',
  'green-emeraude',
  'green-menthe',
  'green-archipel',
  'blue-ecume',
  'blue-cumulus',
  'purple-glycine',
  'pink-macaron',
  'pink-tuile',
  'yellow-tournesol',
  'yellow-moutarde',
  'orange-terre-battue',
  'brown-cafe-creme',
  'brown-caramel',
  'brown-opera',
  'beige-gris-galet',
] as const;

export const major = {
  'green-tilleul-verveine': '#66673d',
  'green-bourgeon': '#447049',
  'green-emeraude': '#297254',
  'green-menthe': '#37635f',
  'green-archipel': '#006a6f',
  'blue-ecume': '#2f4077',
  'blue-cumulus': '#3558a2',
  'purple-glycine': '#6e445a',
  'pink-macaron': '#8d533e',
  'pink-tuile': '#a94645',
  'yellow-tournesol': '#716043',
  'yellow-moutarde': '#695240',
  'orange-terre-battue': '#755348',
  'brown-cafe-creme': '#685c48',
  'brown-caramel': '#845d48',
  'brown-opera': '#745b47',
  'beige-gris-galet': '#6a6156',
};

export const minor = {
  'green-tilleul-verveine': '#b7a73f',
  'green-bourgeon': '#68a532',
  'green-emeraude': '#00a95f',
  'green-menthe': '#009081',
  'green-archipel': '#009099',
  'blue-ecume': '#465f9d',
  'blue-cumulus': '#417dc4',
  'purple-glycine': '#a558a0',
  'pink-macaron': '#e18b76',
  'pink-tuile': '#ce614a',
  'yellow-tournesol': '#c8aa39',
  'yellow-moutarde': '#c3992a',
  'orange-terre-battue': '#e4794a',
  'brown-cafe-creme': '#d1b781',
  'brown-caramel': '#c08c65',
  'brown-opera': '#bd987a',
  'beige-gris-galet': '#aea397',
};

export const decorative = {
  'green-tilleul-verveine': '#fceeac',
  'green-bourgeon': '#c9fcac',
  'green-emeraude': '#c3fad5',
  'green-menthe': '#bafaee',
  'green-archipel': '#c7f6fc',
  'blue-ecume': '#e9edfe',
  'blue-cumulus': '#e6eefe',
  'purple-glycine': '#fee7fc',
  'pink-macaron': '#fee9e6',
  'pink-tuile': '#fee9e7',
  'yellow-tournesol': '#feecc2',
  'yellow-moutarde': '#feebd0',
  'orange-terre-battue': '#fee9e5',
  'brown-cafe-creme': '#f7ecdb',
  'brown-caramel': '#f7ebe5',
  'brown-opera': '#f7ece4',
  'beige-gris-galet': '#f3ede5',
};

export const background = {
  'green-tilleul-verveine': '#fef7da',
  'green-bourgeon': '#e6feda',
  'green-emeraude': '#e3fdeb',
  'green-menthe': '#dffdf7',
  'green-archipel': '#e5fbfd',
  'blue-ecume': '#f4f6fe',
  'blue-cumulus': '#f3f6fe',
  'purple-glycine': '#fef3fd',
  'pink-macaron': '#fef4f2',
  'pink-tuile': '#fef4f3',
  'yellow-tournesol': '#fef6e3',
  'yellow-moutarde': '#fef5e8',
  'orange-terre-battue': '#fef4f2',
  'brown-cafe-creme': '#fbf6ed',
  'brown-caramel': '#fbf5f2',
  'brown-opera': '#fbf5f1',
  'beige-gris-galet': '#f9f6f1',
};

export const motif = {
  'green-tilleul-verveine': '#fbe769',
  'green-bourgeon': '#a9fb68',
  'green-emeraude': '#9ef9be',
  'green-menthe': '#8bf8e7',
  'green-archipel': '#a6f2fa',
  'blue-ecume': '#dee5fd',
  'blue-cumulus': '#dae6fd',
  'purple-glycine': '#fddbfa',
  'pink-macaron': '#fddfda',
  'pink-tuile': '#fddfdb',
  'yellow-tournesol': '#fde39c',
  'yellow-moutarde': '#fde2b5',
  'orange-terre-battue': '#fdd',
  'brown-cafe-creme': '#fdd',
  'brown-caramel': '#fdd',
  'brown-opera': '#fdd',
  'beige-gris-galet': '#fdd',
};

export const majorColors = Object.values(major);
export const minorColors = Object.values(minor);
export const decorativeColors = Object.values(decorative);
export const backgroundColors = Object.values(background);
export const motifColors = Object.values(motif);
